### PR TITLE
Spelling changes

### PR DESCRIPTION
**Pull request by esoleyman**

### CODE REVIEW

**Comment by esoleyman** [comment]
Thank you Sargis!

You have inspired me to push my Syriac / Assyrian localization efforts for Linux.

**Comment by SargisYonan** [comment]
That’s awesome, Emil! Let me know if I can help at all!

**Comment by esoleyman** [comment]
Can you look at the locale file and see if there’s any wrong with it or if any changes should be made?

―
Emil Soleyman-Zomalan, MD FAAEM

**Comment by SargisYonan** [comment]
Hey Emil,
I checked it out, and it looks good I think. Some of the pronunciations for the days of the week, for example, are not the ones I'm used to, but nothing indecipherable.
e.x. ܬܪܵܒ݂ܫܹܒܵܐ vs. ܬܪܹܝܢ ܒܫܹܒܵܐ

I'm exciting to try it out on my linux machine. I'll let you know if I run into anything

**Comment by esoleyman** [comment]
We are used to the Urmiah dialect for days of the week and we write it as we speak it but I’ve looked at multiple sources and the way I’ve put it in the locale is correct. I've checked with George Kiraz at Beth Mardutho and queried Windows 10 for the localization. I've made it similar. The pronunciation is different on who reads it anyways.

ܬܪܵܒ݂ܫܹܒܵܐ (urmiah dialect) vs. ܬܪܹܝܢ ܒܫܲܒܵܐ (classical syriac)

Secondarily, is it better to keep it as ܬܪܹܝܢܒܫܲܒܵܐ vs ܬܪܹܝܢ ܒܫܲܒܵܐ? Windows has it with a space.

―Emil Soleyman-Zomalan, MD FAAEM

**Comment by SargisYonan** [comment]
I think I prefer the way I’m not used to to be honest (the non-urmi way). It makes more sense. I also like the space personally, and it seems to be consistent with the Assyriophile de France dictionary which I trust. Especially since Windows uses the space, it’s probably best to keep the space.

**Comment by esoleyman** [comment]
Perfect. Let me know if you need anything regarding Linux. I’ve been using it exclusively for 20+ years.

―
Emil Soleyman-Zomalan, MD FAAEM

**Comment by SargisYonan** [comment]
Thanks, Emil! I’ll let you know

**Pull request merged**
